### ISSUE TITLE
No plugin.yml on start

### ISSUE THREAD

**Issue by LigerXT5** [redstone/FreshWilderness#6]
Just starting a fresh new server, trying out the plugin.

On start, we get the following:

`[17:37:54] [Server thread/ERROR]: Could not load 'plugins/FreshWilderness.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`

**Comment by MarkehMe** [comment]
Where did you download the jar from?

**Comment by MarkehMe** [comment]
If you got it from spigotmc it looks like they didn't properly replace the reuploaded file.

You can grab it from here: 
https://github.com/redstone/FreshWilderness/releases

**Comment by LigerXT5** [comment]
Yes, it got it from Spigot. I haven't tried your recent release yet. I'll find out if it bugs out tomorrow.

Thanks for the help!
